<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>61f3d679-7c81-4614-b5b8-9954bbfd633f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gateway\TaskFlow.Gateway\TaskFlow.Gateway.csproj" />
    <ProjectReference Include="..\..\Services\Projects\TaskFlow.Projects.Api\TaskFlow.Projects.Api.csproj" />
    <ProjectReference Include="..\..\Services\Tasks\TaskFlow.Tasks.Api\TaskFlow.Tasks.Api.csproj" />
  </ItemGroup>

</Project>
