<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\TaskFlow.ServiceDefaults\TaskFlow.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TaskFlow.Api.Common\TaskFlow.Api.Common.csproj" />
    <ProjectReference Include="..\TaskFlow.Tasks.Infrastructure\TaskFlow.Tasks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
